// Shared candidate dataset — used by all four explorations.
// Keeps vibe comparison honest: same data, different design language.

window.ROLE = {
  title: "Senior Frontend Engineer",
  team: "Payments",
  status: "Open",
  location: "Bangalore / Remote",
  comp: "₹42–58L",
  hiringManager: "Meera Subramaniam",
  postedDaysAgo: 3,
  applications: 47,
  screened: 42,
  pendingReview: 10,
  shortlisted: 1,
  rejected: 15,
};

window.STAGES = [
  { id: "new", label: "New" },
  { id: "screening", label: "Recruiter screening" },
  { id: "shortlisted", label: "Shortlisted" },
  { id: "saved", label: "Saved for later" },
  { id: "rejected", label: "Rejected" },
];

window.CANDIDATES = [
  {
    id: "c1",
    name: "Priya Ramaswamy",
    initials: "PR",
    score: 92,
    stage: "shortlisted",
    email: "priya.ramaswamy@gmail.com",
    phone: "+91 98800 12345",
    location: "Bangalore, IN",
    yoe: 7,
    current: "Sr. Frontend Engineer · Razorpay",
    source: "Referral",
    sourceDetail: "Dev Kapoor",
    appliedAgo: "2d",
    summary: "Led checkout migration to Next.js, drove 40% perf gain, built Razorpay's design system (Blade).",
    strengths: [
      { title: "Deep React + TypeScript", evidence: "7 yrs React, TS since 2019; authored internal style guide." },
      { title: "Design systems leader", evidence: "Built Razorpay Blade — 60+ components, 4 product teams." },
      { title: "Production scale", evidence: "Owned checkout serving 3M+ transactions/day." },
    ],
    gaps: [
      { title: "No Remix exposure", evidence: "Next.js only; our team uses both." },
      { title: "Light testing signal", evidence: "Jest mentioned; no integration/e2e depth." },
      { title: "No explicit mentoring", evidence: "Resume is IC-framed; no leadership of juniors." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: true },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: true },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: true },
      { label: "Performance", pass: true },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: false },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "7" },
      { q: "Authorized to work in India?", a: "Yes" },
      { q: "Earliest start date?", a: "4 weeks notice" },
    ],
  },
  {
    id: "c2",
    name: "Arjun Shetty",
    initials: "AS",
    score: 88,
    stage: "screening",
    email: "arjun.s@protonmail.com",
    phone: "+91 98450 67890",
    location: "Bangalore, IN",
    yoe: 6,
    current: "Frontend Engineer · Swiggy",
    source: "LinkedIn",
    sourceDetail: null,
    appliedAgo: "3d",
    summary: "Owned Swiggy web perf — reduced LCP from 4.1s to 1.8s across restaurant listing flow.",
    strengths: [
      { title: "Performance expert", evidence: "LCP 4.1→1.8s on Swiggy listings; authored team perf playbook." },
      { title: "Next.js production depth", evidence: "Migrated Swiggy web from CRA to Next.js App Router." },
      { title: "TS + testing culture", evidence: "Vitest-first team; 70% coverage on core flows." },
    ],
    gaps: [
      { title: "Not a design-system owner", evidence: "Contributor role, not lead." },
      { title: "Limited a11y signal", evidence: "No WCAG/ARIA mentions." },
      { title: "No mentoring track record", evidence: "No leadership of juniors called out." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: true },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: true },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: true },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: true },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "6" },
      { q: "Authorized to work in India?", a: "Yes" },
      { q: "Earliest start date?", a: "6 weeks notice" },
    ],
  },
  {
    id: "c3",
    name: "Mei Lin Tan",
    initials: "MT",
    score: 85,
    stage: "screening",
    email: "meilin@hey.com",
    phone: "+65 9123 4567",
    location: "Singapore · Remote OK",
    yoe: 5,
    current: "Frontend Engineer · Stripe",
    source: "LinkedIn",
    sourceDetail: null,
    appliedAgo: "1d",
    summary: "Accessibility lead on Stripe Checkout; shipped WCAG 2.2 AA conformance across 14 payment flows.",
    strengths: [
      { title: "Accessibility depth", evidence: "Led WCAG 2.2 AA project on Stripe Checkout (14 flows)." },
      { title: "Rigorous TS", evidence: "Contributed to internal TS linting ruleset; strict mode evangelist." },
      { title: "Remix + Next.js", evidence: "Stripe Docs runs Remix; Checkout runs Next — shipped in both." },
    ],
    gaps: [
      { title: "Smaller scale of ownership", evidence: "IC role; not led multi-team initiatives." },
      { title: "No design system creation", evidence: "Used Stripe's system; didn't build one." },
      { title: "Timezone overlap unclear", evidence: "SG is 2.5h ahead of BLR — workable but not stated." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: true },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: true },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: true },
      { label: "Accessibility", pass: true },
      { label: "Testing depth", pass: true },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "5" },
      { q: "Authorized to work in India?", a: "No — would need remote" },
      { q: "Earliest start date?", a: "8 weeks notice" },
    ],
  },
  {
    id: "c4",
    name: "Daniel Okafor",
    initials: "DO",
    score: 83,
    stage: "new",
    email: "d.okafor@fastmail.com",
    phone: "+44 7700 900123",
    location: "London, UK · Remote",
    yoe: 6,
    current: "Senior Frontend Engineer · Monzo",
    source: "Career page",
    sourceDetail: null,
    appliedAgo: "4d",
    summary: "Built Monzo's internal tooling platform; mentored 3 juniors through career progression.",
    strengths: [
      { title: "Mentoring + leadership", evidence: "Led 3 juniors to mid-level; authored Monzo's FE onboarding." },
      { title: "Strong TS + testing", evidence: "Playwright champion; 85%+ coverage on owned code." },
      { title: "Design partnership", evidence: "Shipped 12 features with design across 2 years." },
    ],
    gaps: [
      { title: "No consumer-scale product", evidence: "Internal tools, not public-facing." },
      { title: "Next.js limited", evidence: "Monzo tools use Remix; Next.js only personal projects." },
      { title: "5h timezone offset", evidence: "London → Bangalore requires shift." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: true },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: false },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: false },
      { label: "Accessibility", pass: true },
      { label: "Testing depth", pass: true },
      { label: "Mentoring", pass: true },
    ],
    qualifying: [
      { q: "Years of production React?", a: "6" },
      { q: "Authorized to work in India?", a: "No — remote only" },
      { q: "Earliest start date?", a: "4 weeks notice" },
    ],
  },
  {
    id: "c5",
    name: "Ananya Iyer",
    initials: "AI",
    score: 79,
    stage: "screening",
    email: "ananya.iyer17@outlook.com",
    phone: "+91 99020 34567",
    location: "Bangalore, IN",
    yoe: 4,
    current: "Frontend Engineer · Unacademy",
    source: "Naukri",
    sourceDetail: null,
    appliedAgo: "2d",
    summary: "Motion + animation specialist; built Unacademy's live-class video UI with React + Framer Motion.",
    strengths: [
      { title: "Animation craft", evidence: "Live-class video UI with complex choreography; Framer Motion depth." },
      { title: "Shipped at scale", evidence: "Unacademy live-class serves 500k+ concurrent students." },
      { title: "Strong React intuition", evidence: "Custom hooks for realtime video sync." },
    ],
    gaps: [
      { title: "TS only 2 years", evidence: "Migrated mid-career; depth less than 3 yrs." },
      { title: "No design-system work", evidence: "Built features, not foundation." },
      { title: "No mentoring signal", evidence: "IC focus only." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: false },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: true },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: true },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: false },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "4" },
      { q: "Authorized to work in India?", a: "Yes" },
      { q: "Earliest start date?", a: "2 weeks notice" },
    ],
  },
  {
    id: "c6",
    name: "Tomás Herrera",
    initials: "TH",
    score: 76,
    stage: "saved",
    email: "tomas.herrera@gmail.com",
    phone: "+54 11 4567 8901",
    location: "Buenos Aires · Remote",
    yoe: 5,
    current: "Frontend Engineer · Mercado Libre",
    source: "LinkedIn",
    sourceDetail: null,
    appliedAgo: "5d",
    summary: "React Native + Web shared-codebase owner at Mercado Libre checkout team.",
    strengths: [
      { title: "Cross-platform React", evidence: "Shared codebase across RN + Web at ML checkout." },
      { title: "Performance discipline", evidence: "Owned Core Web Vitals for ML checkout web." },
      { title: "Payment domain", evidence: "3 yrs in payments specifically — direct relevance." },
    ],
    gaps: [
      { title: "Weak TS signal", evidence: "JS codebase primarily; TS on personal projects." },
      { title: "No design-system ownership", evidence: "Consumer of ML's Andes, not author." },
      { title: "9.5h timezone offset", evidence: "BA → BLR is brutal; async-only workable." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: false },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: true },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: true },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: false },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "5" },
      { q: "Authorized to work in India?", a: "No — remote only" },
      { q: "Earliest start date?", a: "3 weeks notice" },
    ],
  },
  {
    id: "c7",
    name: "Sarah Chen",
    initials: "SC",
    score: 72,
    stage: "new",
    email: "sarahchen.dev@gmail.com",
    phone: "+1 415 555 0127",
    location: "Remote · US",
    yoe: 2,
    current: "Frontend Engineer · Airbnb (contractor)",
    source: "Referral",
    sourceDetail: "Ameya Rao",
    appliedAgo: "1d",
    summary: "Self-taught engineer via bootcamp; strong TS + a11y focus; applied for Senior-level against guidance.",
    strengths: [
      { title: "Strong TypeScript", evidence: "TS from day one; contributed to open-source types library." },
      { title: "Accessibility-first", evidence: "a11y champion at bootcamp; shipped ARIA patterns on Airbnb search." },
      { title: "Referral endorsement", evidence: "Referred by Ameya (staff eng) with explicit note." },
    ],
    gaps: [
      { title: "Only 2 YOE", evidence: "Role asks 3+; significantly under bar." },
      { title: "Contractor, not FT", evidence: "6-month Airbnb contract — not full-time scale." },
      { title: "No production scale", evidence: "Small feature ownership only." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: false },
      { label: "TypeScript", pass: true },
      { label: "Modern framework", pass: true },
      { label: "Production-scale experience", pass: false },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: false },
      { label: "Accessibility", pass: true },
      { label: "Testing depth", pass: false },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "2" },
      { q: "Authorized to work in India?", a: "No — remote only" },
      { q: "Earliest start date?", a: "Immediate" },
    ],
  },
  {
    id: "c8",
    name: "Kabir Malhotra",
    initials: "KM",
    score: 68,
    stage: "rejected",
    email: "kabir.malhotra@gmail.com",
    phone: "+91 98670 23456",
    location: "Bangalore, IN",
    yoe: 12,
    current: "Principal Engineer · Flipkart",
    source: "Naukri",
    sourceDetail: null,
    appliedAgo: "6d",
    summary: "12 YOE but predominantly backend; recent pivot toward frontend architecture.",
    strengths: [
      { title: "Systems architecture depth", evidence: "12 YOE; principal-level scope at Flipkart." },
      { title: "Distributed systems knowledge", evidence: "Owned Flipkart checkout backend at peak traffic." },
      { title: "Strong fundamentals", evidence: "CS-rigorous; published 2 papers on distributed consensus." },
    ],
    gaps: [
      { title: "Primarily backend", evidence: "Frontend work is <2 yrs of the 12." },
      { title: "Modern frameworks shallow", evidence: "Next.js/Remix exposure is limited." },
      { title: "Over-levelled for role", evidence: "Principal applying for Senior — flight risk." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: false },
      { label: "TypeScript", pass: true },
      { label: "Modern framework", pass: false },
      { label: "Production-scale experience", pass: true },
      { label: "Designer collaboration", pass: false },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: true },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: true },
      { label: "Mentoring", pass: true },
    ],
    qualifying: [
      { q: "Years of production React?", a: "2" },
      { q: "Authorized to work in India?", a: "Yes" },
      { q: "Earliest start date?", a: "8 weeks notice" },
    ],
  },
  {
    id: "c9",
    name: "Elena Marchetti",
    initials: "EM",
    score: 65,
    stage: "new",
    email: "elena.marchetti.it@gmail.com",
    phone: "+39 340 123 4567",
    location: "Milan, IT · Remote",
    yoe: 4,
    current: "Freelance · Various clients",
    source: "Career page",
    sourceDetail: null,
    appliedAgo: "3d",
    summary: "Freelance frontend; strong CSS and animation craft; TS picked up mid-career.",
    strengths: [
      { title: "Elite CSS craft", evidence: "Award-winning CSS art; contributed to Tailwind plugin ecosystem." },
      { title: "Design sensibility", evidence: "Comes from a design background; strong visual language." },
      { title: "Independent operator", evidence: "Freelance: direct client-facing, full ownership." },
    ],
    gaps: [
      { title: "Weaker TypeScript", evidence: "Started learning 2023; not depth." },
      { title: "No team-scale production", evidence: "Solo freelance, not multi-team." },
      { title: "Framework breadth low", evidence: "React yes, Next.js minimal, Remix none." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: true },
      { label: "TypeScript", pass: false },
      { label: "Modern framework", pass: false },
      { label: "Production-scale experience", pass: false },
      { label: "Designer collaboration", pass: true },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: false },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: false },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "4" },
      { q: "Authorized to work in India?", a: "No — remote only" },
      { q: "Earliest start date?", a: "Immediate" },
    ],
  },
  {
    id: "c10",
    name: "Rohan Nair",
    initials: "RN",
    score: 58,
    stage: "rejected",
    email: "rohan.nair04@gmail.com",
    phone: "+91 97890 12345",
    location: "Mumbai, IN",
    yoe: 2,
    current: "Junior Engineer · early-stage startup",
    source: "Naukri",
    sourceDetail: null,
    appliedAgo: "4d",
    summary: "1.5 YOE at a seed-stage startup; applied for Senior role despite clear under-bar.",
    strengths: [
      { title: "Scrappy shipper", evidence: "Seed-stage startup: wore many hats, shipped fast." },
      { title: "React basics solid", evidence: "1.5 yrs React, TS for last 6 months." },
      { title: "Hungry", evidence: "Clear growth trajectory; strong cover letter." },
    ],
    gaps: [
      { title: "Significantly under-levelled", evidence: "Senior role asks 5+; candidate has 2." },
      { title: "No production scale", evidence: "Startup with <10k MAU." },
      { title: "Framework + testing thin", evidence: "Create-React-App; no Next.js, no tests." },
    ],
    mustHaves: [
      { label: "React (3+ yrs)", pass: false },
      { label: "TypeScript", pass: false },
      { label: "Modern framework", pass: false },
      { label: "Production-scale experience", pass: false },
      { label: "Designer collaboration", pass: false },
    ],
    niceHaves: [
      { label: "Design systems", pass: false },
      { label: "Performance", pass: false },
      { label: "Accessibility", pass: false },
      { label: "Testing depth", pass: false },
      { label: "Mentoring", pass: false },
    ],
    qualifying: [
      { q: "Years of production React?", a: "1.5" },
      { q: "Authorized to work in India?", a: "Yes" },
      { q: "Earliest start date?", a: "Immediate" },
    ],
  },
];
